CREATE TABLE ELEMENT_MAPPING (
   AS_FIELDS VARCHAR(50) ,
   ELEMENTS VARCHAR(50) ,
   ENABLE VARCHAR(1) ,
   FEEDER VARCHAR(50) ,
   ROLE_NAME VARCHAR(50),
   PRIMARY KEY(ELEMENTS,ENABLE,role_Name)
);




CREATE TABLE USER_ROLES(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID VARCHAR(50) ,
  ROLE_NAME VARCHAR(50) ,
  ROLE_DESCRIPTION VARCHAR(100) ,
  ICA VARCHAR(50) ,
  STATUS VARCHAR(10) ,
  CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATED_TIMESTAMP TIMESTAMP
);


CREATE TABLE ROLE_MAPPING (
  ROLE_NAME VARCHAR(50) PRIMARY KEY ,
  DOWNLOAD_DETAIL_COUNT VARCHAR(50) ,
  DOWNLOAD_SUMMARY_COUNT VARCHAR(50) ,
  SUMMARY_RESPONSE_COUNT VARCHAR(50) ,
  DETAIL_RESPONSE_COUNT VARCHAR(50)
);




