CREATE TABLE USER_ROLES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID VARCHAR(50) ,
  ROLE_NAME VARCHAR(50) ,
  ROLE_DESCRIPTION VARCHAR(100) ,
  ICA VARCHAR(50) ,
  STATUS VARCHAR(10) ,
  CREATED_TIMESTAMP VARCHAR (50),
  LAST_UPDATED_TIMESTAMP VARCHAR (50),
);


CREATE TABLE ROLE_MAPPING (
  ROLE_NAME VARCHAR(50) ,
  DOWNLOAD_DETAIL_COUNT VARCHAR(50) ,
  DOWNLOAD_SUMMARY_COUNT VARCHAR(50) ,
  SUMMARY_RESPONSE_COUNT VARCHAR(50) ,
  DETAIL_RESPONSE_COUNT VARCHAR(50)
);


CREATE TABLE ELEMENT_MAPPING (
   AS VARCHAR(50) ,
   ELEMENTS VARCHAR(50) ,
   ENABLE VARCHAR(1) ,
   FEEDER VARCHAR(50) ,
   ROLE_NAME VARCHAR(50)
);

